development:
  adapter:   mysql2
  encoding:  utf8
  host:      localhost
  pool: 5
  username:  root
  password:  
  database:  sinatra_blog_development

test:
  adapter:   mysql2
  host:      localhost
  username:  root
  password:  
  database:  sinatra_blog_test
  encoding:  utf8